### ISSUE TITLE
Not spectified dependencies in package.json.

### ISSUE THREAD

**Issue by Hazealign** [therne/cottage#2]
Thanks for awesome project. 👍 
I think should have to declare dependencies in npm releases.

```
% node index.js                                                         
module.js:442
    throw err;

Error: Cannot find module 'methods'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (../project/node_modules/cottage/lib/route.js:2:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)`
```

**Comment by therne** [comment]
Resolved
