### ISSUE TITLE
Rest/Spread  functionality not natively supported in 7.*

### ISSUE THREAD

**Issue by cavejay** [therne/cottage#20]
Just noticed when attempting to run Cottage with Node 7.7.x that there was an immediate stack trace with the following. It appears as though you've written Cottage for Node 8 while saying it supports earlier: 

```
C:\node_modules\cottage\lib\router.js:29
            ...options
            ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\node_modules\cottage\lib\application.js:3:16)

cmd>node -v
v7.7.3
```

**Comment by therne** [comment]
Sorry for late response 😢 That was my mistake! I'll fix it now and will add it to the Travis coverage.
Thanks for reporting the issue. 🥇
